name: 'Update deploy tag'
description: 'Update the tag for projet deploy'

inputs:
  token:
    description: 'The access token for the private repository'
    required: true
  owner:
    description: 'The owner of the private repository'
    required: true
  repo:
    description: 'The name of the private repository'
    required: true
  branch:
    description: 'The branch to update in the private repository'
    required: true
  path:
    description: 'The path to the YAML file in the private repository'
    required: true
outputs:
  version:
    description: 'The version retrieved from package.json'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Version from package.json
      id: get_version
      shell: bash
      run: echo "::set-output name=version::$(grep -Eo '"version":.*?[^\\]",' package.json | awk -F'"' '{print $4}')"

    - name: Clone the private repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.owner }}/${{ inputs.repo }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}

    - name: Update version in YAML file
      shell: bash
      run: |
        sed -i "s/@@img_tag@@/'${{ steps.get_version.outputs.version }}'/g" ${{ inputs.path }}

    - name: Commit changes
      shell: bash
      run: |
        git config user.email "admin@bibliotheque-numerique.fr"
        git config user.name "GitHub Action"
        git add ${{ inputs.path }}
        git commit -m "Update version to ${{ steps.get_version.outputs.version }}"
        git push origin ${{ inputs.branch }} --force

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ inputs.token }}
#        branch: ${{ inputs.branch }}
#        directory: .
#        force: true
#        cleanup: false
#        allow_empty_commit: false
#        commit_message: "Update version to ${{ steps.get_version.outputs.version }}"
#        committer: GitHub Action <admin@bibliotheque-numerique.fr>