name: 'Update deploy tag'
description: 'Update the tag for projet deploy'

inputs:
  token:
    description: 'The access token for the private repository'
    required: true
  owner:
    description: 'The owner of the private repository'
    required: true
  repo:
    description: 'The name of the private repository'
    required: true
  branch:
    description: 'The branch to update in the private repository'
    required: true
  path:
    description: 'The path to the YAML file in the private repository'
    required: true
outputs:
  version:
    description: 'The version retrieved from package.json'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Version from package.json
      id: get_version
      shell: bash
      run: echo "::set-output name=version::$(grep -Eo '"version":.*?[^\\]",' package.json | awk -F'"' '{print $4}')"

    - name: Clone the private repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.owner }}/${{ inputs.repo }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}
        path: ${{ inputs.repo }}

    - name: Update version in YAML file
      working-directory: ${{ inputs.repo }}
      shell: bash
      run: |
        sed -i "s|biblionum/bibliotheque_numerique-front:.*$|biblionum/bibliotheque_numerique-front:${{ steps.get_version.outputs.version }}|" ${{ inputs.path }}
        sed -i "s|biblionum/bibliotheque_numerique-back:.*$|biblionum/bibliotheque_numerique-back:${{ steps.get_version.outputs.version }}|" ${{ inputs.path }}

    - name: Commit changes
      working-directory: ${{ inputs.repo }}
      shell: bash
      run: |
        git config user.email "admin@bibliotheque-numerique.fr"
        git config user.name "GitHub Action"
        git add ${{ inputs.path }}
        git commit -m "Update image version to ${{ steps.get_version.outputs.version }}"
        git push origin ${{ inputs.branch }} --force
