include:
  - local: "/ci/includes/node.yml"
  - local: "/ci/includes/rules.yml"
  - local: "/ci/includes/docker.yml"
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

default:
  image: node:18
  before_script:
    - export TAG=$(grep -Eo '"version":.*?[^\\]",' package.json | awk -F'"' '{print $4}')

variables:
  DOCKERFILE: Dockerfile
  PROJECT_NAME: bibliotheque-numerique
  PROJECT_ORGANISATION: ministere-interieur
  PROJECT_PATH: ${PROJECT_ORGANISATION}-${PROJECT_NAME}
  REGISTRY_URL: "${IMAGE_REPOSITORY}"
  CYPRESS_CACHE_FOLDER: "/tmp"

stages:
  - read-secret
  - test-sonar
  - docker-test
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

test_front:
  variables:
    WORKING_DIR: apps/client
  stage: test-sonar
  allow_failure: true
  extends:
    - .node:sonar

test_rnf_front:
  variables:
    WORKING_DIR: apps/rnf-client
  stage: test-sonar
  allow_failure: true
  extends:
    - .node:sonar

test_back:
  variables:
    WORKING_DIR: apps/server
  stage: test-sonar
  allow_failure: true
  extends:
    - .node:sonar

test_rnf_back:
  variables:
    WORKING_DIR: apps/rnf-server
  stage: test-sonar
  allow_failure: true
  extends:
    - .node:sonar

test_http_proxy:
  variables:
    WORKING_DIR: apps/http-proxy
  stage: test-sonar
  allow_failure: true
  extends:
    - .node:sonar

test_docker_front:
  variables:
    WORKING_DIR: 'apps/client'
    IMAGE_NAME: 'bibliotheque_numerique-front'
    DOCKERFILE: 'Dockerfile'
  stage: docker-test
  allow_failure: true
  extends:
    - .docker:test

test_docker_rnf_front:
  variables:
    WORKING_DIR: 'apps/rnf-client'
    IMAGE_NAME: 'rnf-front'
    DOCKERFILE: 'Dockerfile'
  stage: docker-test
  allow_failure: true
  extends:
    - .docker:test

test_docker_back:
  image: docker:stable
  variables:
    WORKING_DIR: 'apps/server'
    IMAGE_NAME: 'bibliotheque_numerique-back'
    DOCKERFILE: 'Dockerfile'
  stage: docker-test
  allow_failure: true
  extends:
    - .docker:test

test_docker_rnf_back:
  image: docker:stable
  variables:
    WORKING_DIR: 'apps/rnf-server'
    IMAGE_NAME: 'rnf-back'
    DOCKERFILE: 'Dockerfile'
  stage: docker-test
  allow_failure: true
  extends:
    - .docker:test

test_docker_http_proxy:
  image: docker:stable
  variables:
    WORKING_DIR: 'apps/http-proxy'
    IMAGE_NAME: 'http-proxy'
    DOCKERFILE: 'Dockerfile'
  stage: docker-test
  allow_failure: true
  extends:
    - .docker:test

docker_build_front:
  variables:
    WORKING_DIR: 'apps/client'
    IMAGE_NAME: 'bibliotheque_numerique-front'
    DOCKERFILE: 'Dockerfile'
  stage: docker-build
  extends:
    - .kaniko:simple-build-push

docker_build_rnf_front:
  variables:
    WORKING_DIR: 'apps/rnf-client'
    IMAGE_NAME: 'rnf-front'
    DOCKERFILE: 'Dockerfile'
  stage: docker-build
  extends:
    - .kaniko:simple-build-push

docker_build_back:
  variables:
    WORKING_DIR: 'apps/server'
    IMAGE_NAME: 'bibliotheque_numerique-back'
    DOCKERFILE: 'Dockerfile'
  stage: docker-build
  extends:
    - .kaniko:simple-build-push

docker_build_rnf_back:
  variables:
    WORKING_DIR: 'apps/rnf-server'
    IMAGE_NAME: 'rnf-back'
    DOCKERFILE: 'Dockerfile'
  stage: docker-build
  extends:
    - .kaniko:simple-build-push


docker_build_http_proxy:
  variables:
    WORKING_DIR: 'apps/http-proxy'
    IMAGE_NAME: 'http-proxy'
    DOCKERFILE: 'Dockerfile'
  stage: docker-build
  extends:
    - .kaniko:simple-build-push
