FROM node:lts as base

WORKDIR /app

RUN npm i -g turbo

RUN chown node:node /app
USER node

COPY . .
RUN turbo prune --scope=@biblio-num/server --docker


FROM node:lts AS builder

WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=base /app/out/json/ .
COPY --from=base /app/out/package-lock.json ./package-lock.json
RUN npm ci
COPY --from=base /app/out/full/ .

CMD ["npm", "run", "dev:server-in-docker"]