/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgGridAttachmentCell: typeof import('./components/ag-grid/AgGridAttachmentCell.vue')['default']
    AgGridMultiValueCell: typeof import('./components/ag-grid/AgGridMultiValueCell.vue')['default']
    AgGridServerSide: typeof import('./components/ag-grid/server-side/AgGridServerSide.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    BiblioNumDataTableAgGrid: typeof import('./components/BiblioNumDataTableAgGrid.vue')['default']
    BnCheckerPassword: typeof import('./components/BnCheckerPassword.vue')['default']
    CheckRenderer: typeof import('./components/ag-grid/CheckRenderer.vue')['default']
    CprCheckRenderer: typeof import('./components/ag-grid/CprCheckRenderer.vue')['default']
    DelayStateBadge: typeof import('./components/Badges/DelayStateBadge.vue')['default']
    DisplayLabelsValues: typeof import('./components/DisplayLabelsValues.vue')['default']
    DossierStateRenderer: typeof import('./components/ag-grid/DossierStateRenderer.vue')['default']
    DsfrBadge: typeof import('@gouvminint/vue-dsfr')['DsfrBadge']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTag: typeof import('@gouvminint/vue-dsfr')['DsfrTag']
    DsfrWarningButton: typeof import('./components/dsfr-extends/dsfr-warning-button.vue')['default']
    InfoContact: typeof import('./components/InfoContact.vue')['default']
    LayoutAccueil: typeof import('./components/Layout/LayoutAccueil.vue')['default']
    LayoutBanner: typeof import('./components/Layout/LayoutBanner.vue')['default']
    LayoutFiche: typeof import('./components/Layout/LayoutFiche.vue')['default']
    LayoutList: typeof import('./components/Layout/LayoutList.vue')['default']
    OrganismeBadge: typeof import('./components/Badges/OrganismeBadge.vue')['default']
    OrganismeBadgesRenderer: typeof import('./components/Badges/OrganismeBadgesRenderer.vue')['default']
    PasswordHint: typeof import('./components/PasswordHint.vue')['default']
    PermissionOptionNumber: typeof import('./components/PermissionOption/PermissionOptionNumber.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RoleBadge: typeof import('./components/Badges/RoleBadge.vue')['default']
    RoleBadgesRenderer: typeof import('./components/Badges/RoleBadgesRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./components/Badges/StatusBadge.vue')['default']
    StatusBadgesRenderer: typeof import('./components/Badges/StatusBadgesRenderer.vue')['default']
    TableCellAction: typeof import('./components/TableCellAction.vue')['default']
    ToggleInputPassword: typeof import('./components/ToggleInputPassword.vue')['default']
    TransitionExpand: typeof import('./components/TransitionExpand.vue')['default']
    VIcon: typeof import('oh-vue-icons')['OhVueIcon']
  }
}
