export {
  CoTrash,
  RiAddCircleLine,
  RiBarChartBoxLine,
  RiCheckLine,
  RiCheckboxBlankCircleLine,
  RiCheckboxCircleFill,
  RiCloseLine,
  RiDeleteBinLine,
  RiExternalLinkFill,
  RiEyeFill,
  RiFileDownloadFill,
  RiFileList2Fill,
  RiFileList2Line,
  RiFilterOffLine,
  RiFlagLine,
  RiHome2Line,
  RiHome4Line,
  RiIndeterminateCircleLine,
  RiLogoutBoxRLine,
  RiPencilLine,
  RiRefreshLine,
  RiSearchLine,
  RiShieldStarLine,
  RiSortDesc,
  RiSubtractLine,
} from 'oh-vue-icons/icons'
