services:
  server:
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    image: biblio-num/server:prod
    container_name: biblio-num_server
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - biblio-num-network
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_DB: ${POSTGRES_DB:-biblio-num}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      DS_API_URL: ${DS_API_URL}
      DS_API_TOKEN: ${DS_API_TOKEN}
      SMTP_SERVER: ${SMTP_SERVER:-localhost}
      SMTP_PORT: ${SMTP_PORT:- 1025}
      LOG_DATE_FORMAT: "DD/MM/YYYY HH:mm:ss"
      JWT_SECRET: ${JWT_SECRET:-biblio-num-jwt-secret}
      SESSION_SECRET: ${SESSION_SECRET:-biblio-num-session-secret}


networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
