services:
  db:
    image: postgres:14.5
    container_name: biblio-num_db-test
    restart: always
    environment:
      POSTGRES_DB: biblio-num-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - biblio-num-test-network

networks:
  biblio-num-test-network:
    name: biblio-num-test-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
