services:
  db:
    image: postgres:14.5
    container_name: biblio-num_db
    restart: always
    environment:
      POSTGRES_DB: biblio-num
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: biblio-num-db-volume
        target: /var/lib/postgresql/data
    networks:
      - biblio-num-network

networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  biblio-num-db-volume:
