services:
  server:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    image: biblio-num/server:dev
    container_name: biblio-num_server
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    networks:
      - biblio-num-network
    command: npm run dev
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: biblio-num
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DS_API_URL: ${DS_API_URL}
      DS_API_TOKEN: ${DS_API_TOKEN}
      FORCE_COLOR: 1
      DEBUG: 1

  pgadmin:
    image: dpage/pgadmin4
    container_name: biblio-num_dbadmin
    depends_on:
      - db
    ports:
      - "3010:80"
    volumes:
      - type: volume
        source: biblio-num-pgadmin-volume
        target: /var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - biblio-num-network

networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  biblio-num-pgadmin-volume:
