services:
  db:
    image: postgres:14.5
    container_name: biblio-num_db-test
    restart: always
    environment:
      POSTGRES_DB: biblio-num-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - biblio-num-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: biblio-num_dbadmin
    depends_on:
      - db
    ports:
      - "3010:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - biblio-num-network

networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
