services:
  server:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    image: biblio-num/server:dev
    container_name: biblio-num_server
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    networks:
      - biblio-num-network
    command: npm run dev
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: biblio-num
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DS_API_URL: ${DS_API_URL}
      DS_API_TOKEN: ${DS_API_TOKEN}
      FORCE_COLOR: 1
      DEBUG: 1
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025

  pgadmin:
    image: dpage/pgadmin4
    container_name: biblio-num_dbadmin
    depends_on:
      - db
    ports:
      - "3010:80"
    volumes:
      - type: volume
        source: biblio-num-pgadmin-volume
        target: /var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - biblio-num-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
        - 1025:1025
        - 8025:8025
    networks:
      - biblio-num-network

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: biblio-num_keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: user
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - 8088:8080
    depends_on:
      - db
    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import
    command: start-dev --import-realm
    networks:
      - biblio-num-network

  s3:
    image: quay.io/minio/minio:RELEASE.2023-01-20T02-05-44Z
    container_name: biblio-num_minio
    environment:
      MINIO_ROOT_USER: s3_biblio-num_minio # MINIO_ACCESS_KEY = MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: s3_biblio-num_minio # MINIO_SECRET_KEY = MINIO_ROOT_PASSWORD
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - type: volume
        source: biblio-num-s3-volume
        target: /data
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      - biblio-num-network

networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  biblio-num-pgadmin-volume:
  biblio-num-s3-volume:
