services:
  server: 
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    image: biblio-num/server:dev
    container_name: biblio-num_server
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - biblio-num-server-node_modules:/app/node_modules
    networks:
      - biblio-num-network
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: biblio-num
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      API_URL: ${API_URL}
      API_TOKEN: ${API_TOKEN}

networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  biblio-num-server-node_modules:
