export const demarche2 = {
  demarche: {
    id: 'UHJvY2VkdXJlLTI=',
    number: 2,
    title: 'Demo procedure 20220927',
    description: 'Demo procedure 20220927',
    state: 'publiee',
    dateCreation: '2022-09-27T15:57:47+02:00',
    dateDepublication: null,
    dateDerniereModification: '2022-09-27T16:11:49+02:00',
    dateFermeture: null,
    datePublication: '2022-09-27T16:11:49+02:00',
    declarative: '',
    draftRevision: {
      id: 'UHJvY2VkdXJlUmV2aXNpb24tNA==',
      champDescriptors: [
        {
          id: 'Q2hhbXAtNg==',
          type: 'text',
          label: "Saisir le n°RNA de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtNw==',
          type: 'yes_no',
          label: "L'association ou la congrégation ne dispose pas de n° RNA",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOA==',
          type: 'departements',
          label: 'Département de rattachement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOQ==',
          type: 'text',
          label: "Titre de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTA=',
          type: 'text',
          label: 'Adresse du siège social',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTI=',
          type: 'text',
          label: 'Numéro de téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTE=',
          type: 'email',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTQ=',
          type: 'text',
          label: 'Site internet',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTU=',
          type: 'text',
          label: 'Civilité',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTY=',
          type: 'text',
          label: 'NOM',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTc=',
          type: 'text',
          label: 'Prénom',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTg=',
          type: 'address',
          label: 'Adresse',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTk=',
          type: 'text',
          label: 'N° appartement, boîte aux lettres, étage, couloir',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjA=',
          type: 'text',
          label: 'Immeuble - Bâtiment - Résidence',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjE=',
          type: 'text',
          label: 'Lieu dit, Boîte postale',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjI=',
          type: 'phone',
          label: 'Téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjM=',
          type: 'text',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjQ=',
          type: 'textarea',
          label: 'Type de financement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjU=',
          type: 'text',
          label: 'Chargement de la matrice complétée de la déclaration',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjY=',
          type: 'yes_no',
          label: 'Dossier sensible ?',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
      ],
      annotationDescriptors: [],
    },
    publishedRevision: {
      id: 'UHJvY2VkdXJlUmV2aXNpb24tMw==',
      champDescriptors: [
        {
          id: 'Q2hhbXAtNg==',
          type: 'text',
          label: "Saisir le n°RNA de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtNw==',
          type: 'yes_no',
          label: "L'association ou la congrégation ne dispose pas de n° RNA",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOA==',
          type: 'departements',
          label: 'Département de rattachement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOQ==',
          type: 'text',
          label: "Titre de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTA=',
          type: 'text',
          label: 'Adresse du siège social',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTI=',
          type: 'text',
          label: 'Numéro de téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTE=',
          type: 'email',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTQ=',
          type: 'text',
          label: 'Site internet',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTU=',
          type: 'text',
          label: 'Civilité',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTY=',
          type: 'text',
          label: 'NOM',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTc=',
          type: 'text',
          label: 'Prénom',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTg=',
          type: 'address',
          label: 'Adresse',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTk=',
          type: 'text',
          label: 'N° appartement, boîte aux lettres, étage, couloir',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjA=',
          type: 'text',
          label: 'Immeuble - Bâtiment - Résidence',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjE=',
          type: 'text',
          label: 'Lieu dit, Boîte postale',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjI=',
          type: 'phone',
          label: 'Téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjM=',
          type: 'text',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjQ=',
          type: 'textarea',
          label: 'Type de financement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjU=',
          type: 'text',
          label: 'Chargement de la matrice complétée de la déclaration',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjY=',
          type: 'yes_no',
          label: 'Dossier sensible ?',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
      ],
      annotationDescriptors: [],
    },
    revisions: [
      {
        id: 'UHJvY2VkdXJlUmV2aXNpb24tMw==',
        champDescriptors: [
          {
            id: 'Q2hhbXAtNg==',
            type: 'text',
            label: "Saisir le n°RNA de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtNw==',
            type: 'yes_no',
            label: "L'association ou la congrégation ne dispose pas de n° RNA",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOA==',
            type: 'departements',
            label: 'Département de rattachement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOQ==',
            type: 'text',
            label: "Titre de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTA=',
            type: 'text',
            label: 'Adresse du siège social',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTI=',
            type: 'text',
            label: 'Numéro de téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTE=',
            type: 'email',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTQ=',
            type: 'text',
            label: 'Site internet',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTU=',
            type: 'text',
            label: 'Civilité',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTY=',
            type: 'text',
            label: 'NOM',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTc=',
            type: 'text',
            label: 'Prénom',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTg=',
            type: 'address',
            label: 'Adresse',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTk=',
            type: 'text',
            label: 'N° appartement, boîte aux lettres, étage, couloir',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjA=',
            type: 'text',
            label: 'Immeuble - Bâtiment - Résidence',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjE=',
            type: 'text',
            label: 'Lieu dit, Boîte postale',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjI=',
            type: 'phone',
            label: 'Téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjM=',
            type: 'text',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjQ=',
            type: 'textarea',
            label: 'Type de financement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjU=',
            type: 'text',
            label: 'Chargement de la matrice complétée de la déclaration',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjY=',
            type: 'yes_no',
            label: 'Dossier sensible ?',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
        ],
        annotationDescriptors: [],
      },
      {
        id: 'UHJvY2VkdXJlUmV2aXNpb24tNA==',
        champDescriptors: [
          {
            id: 'Q2hhbXAtNg==',
            type: 'text',
            label: "Saisir le n°RNA de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtNw==',
            type: 'yes_no',
            label: "L'association ou la congrégation ne dispose pas de n° RNA",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOA==',
            type: 'departements',
            label: 'Département de rattachement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOQ==',
            type: 'text',
            label: "Titre de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTA=',
            type: 'text',
            label: 'Adresse du siège social',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTI=',
            type: 'text',
            label: 'Numéro de téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTE=',
            type: 'email',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTQ=',
            type: 'text',
            label: 'Site internet',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTU=',
            type: 'text',
            label: 'Civilité',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTY=',
            type: 'text',
            label: 'NOM',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTc=',
            type: 'text',
            label: 'Prénom',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTg=',
            type: 'address',
            label: 'Adresse',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTk=',
            type: 'text',
            label: 'N° appartement, boîte aux lettres, étage, couloir',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjA=',
            type: 'text',
            label: 'Immeuble - Bâtiment - Résidence',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjE=',
            type: 'text',
            label: 'Lieu dit, Boîte postale',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjI=',
            type: 'phone',
            label: 'Téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjM=',
            type: 'text',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjQ=',
            type: 'textarea',
            label: 'Type de financement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjU=',
            type: 'text',
            label: 'Chargement de la matrice complétée de la déclaration',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjY=',
            type: 'yes_no',
            label: 'Dossier sensible ?',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
        ],
        annotationDescriptors: [],
      },
    ],
    groupeInstructeurs: [
      {
        id: 'R3JvdXBlSW5zdHJ1Y3RldXItMg==',
        number: 2,
        label: 'défaut',
        instructeurs: [
          {
            id: 'SW5zdHJ1Y3RldXItMg==',
            email: 'mail@peng-fei.name',
          },
          {
            id: 'SW5zdHJ1Y3RldXItMw==',
            email: 'me@bastienchevallier.com',
          },
        ],
      },
    ],
    service: {
      id: 'U2VydmljZS0y',
      nom: 'DLPAJ',
      organisme: 'Direction des libertés publiques et des affaires juridiques',
      siret: '38103128500491',
      typeOrganisme: 'administration_centrale',
    },
  },
}

export const demarche1 = {
  demarche: {
    id: 'UHJvY2VkdXJlLTI=',
    number: 2,
    title: 'Demo procedure 20220927',
    description: 'Demo procedure 20220927',
    state: 'publiee',
    dateCreation: '2022-09-27T15:57:47+02:00',
    dateDepublication: null,
    dateDerniereModification: '2022-09-27T16:11:49+02:00',
    dateFermeture: null,
    datePublication: '2022-09-27T16:11:49+02:00',
    declarative: 'en_instruction',
    draftRevision: {
      id: 'UHJvY2VkdXJlUmV2aXNpb24tNA==',
      champDescriptors: [
        {
          id: 'Q2hhbXAtNg==',
          type: 'text',
          label: "Saisir le n°RNA de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtNw==',
          type: 'yes_no',
          label: "L'association ou la congrégation ne dispose pas de n° RNA",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOA==',
          type: 'departements',
          label: 'Département de rattachement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOQ==',
          type: 'text',
          label: "Titre de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTA=',
          type: 'text',
          label: 'Adresse du siège social',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTI=',
          type: 'text',
          label: 'Numéro de téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTE=',
          type: 'email',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTQ=',
          type: 'text',
          label: 'Site internet',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTU=',
          type: 'text',
          label: 'Civilité',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTY=',
          type: 'text',
          label: 'NOM',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTc=',
          type: 'text',
          label: 'Prénom',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTg=',
          type: 'address',
          label: 'Adresse',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTk=',
          type: 'text',
          label: 'N° appartement, boîte aux lettres, étage, couloir',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjA=',
          type: 'text',
          label: 'Immeuble - Bâtiment - Résidence',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjE=',
          type: 'text',
          label: 'Lieu dit, Boîte postale',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjI=',
          type: 'phone',
          label: 'Téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjM=',
          type: 'text',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjQ=',
          type: 'textarea',
          label: 'Type de financement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjU=',
          type: 'text',
          label: 'Chargement de la matrice complétée de la déclaration',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjY=',
          type: 'yes_no',
          label: 'Dossier sensible ?',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
      ],
      annotationDescriptors: [],
    },
    publishedRevision: {
      id: 'UHJvY2VkdXJlUmV2aXNpb24tMw==',
      champDescriptors: [
        {
          id: 'Q2hhbXAtNg==',
          type: 'text',
          label: "Saisir le n°RNA de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtNw==',
          type: 'yes_no',
          label: "L'association ou la congrégation ne dispose pas de n° RNA",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOA==',
          type: 'departements',
          label: 'Département de rattachement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtOQ==',
          type: 'text',
          label: "Titre de l'association",
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTA=',
          type: 'text',
          label: 'Adresse du siège social',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTI=',
          type: 'text',
          label: 'Numéro de téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTE=',
          type: 'email',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTQ=',
          type: 'text',
          label: 'Site internet',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTU=',
          type: 'text',
          label: 'Civilité',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTY=',
          type: 'text',
          label: 'NOM',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTc=',
          type: 'text',
          label: 'Prénom',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTg=',
          type: 'address',
          label: 'Adresse',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMTk=',
          type: 'text',
          label: 'N° appartement, boîte aux lettres, étage, couloir',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjA=',
          type: 'text',
          label: 'Immeuble - Bâtiment - Résidence',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjE=',
          type: 'text',
          label: 'Lieu dit, Boîte postale',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjI=',
          type: 'phone',
          label: 'Téléphone',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjM=',
          type: 'text',
          label: 'Courriel de contact',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjQ=',
          type: 'textarea',
          label: 'Type de financement',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjU=',
          type: 'text',
          label: 'Chargement de la matrice complétée de la déclaration',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
        {
          id: 'Q2hhbXAtMjY=',
          type: 'yes_no',
          label: 'Dossier sensible ?',
          description: '',
          required: false,
          options: null,
          champDescriptors: null,
        },
      ],
      annotationDescriptors: [],
    },
    revisions: [
      {
        id: 'UHJvY2VkdXJlUmV2aXNpb24tMw==',
        champDescriptors: [
          {
            id: 'Q2hhbXAtNg==',
            type: 'text',
            label: "Saisir le n°RNA de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtNw==',
            type: 'yes_no',
            label: "L'association ou la congrégation ne dispose pas de n° RNA",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOA==',
            type: 'departements',
            label: 'Département de rattachement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOQ==',
            type: 'text',
            label: "Titre de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTA=',
            type: 'text',
            label: 'Adresse du siège social',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTI=',
            type: 'text',
            label: 'Numéro de téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTE=',
            type: 'email',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTQ=',
            type: 'text',
            label: 'Site internet',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTU=',
            type: 'text',
            label: 'Civilité',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTY=',
            type: 'text',
            label: 'NOM',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTc=',
            type: 'text',
            label: 'Prénom',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTg=',
            type: 'address',
            label: 'Adresse',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTk=',
            type: 'text',
            label: 'N° appartement, boîte aux lettres, étage, couloir',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjA=',
            type: 'text',
            label: 'Immeuble - Bâtiment - Résidence',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjE=',
            type: 'text',
            label: 'Lieu dit, Boîte postale',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjI=',
            type: 'phone',
            label: 'Téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjM=',
            type: 'text',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjQ=',
            type: 'textarea',
            label: 'Type de financement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjU=',
            type: 'text',
            label: 'Chargement de la matrice complétée de la déclaration',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjY=',
            type: 'yes_no',
            label: 'Dossier sensible ?',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
        ],
        annotationDescriptors: [],
      },
      {
        id: 'UHJvY2VkdXJlUmV2aXNpb24tNA==',
        champDescriptors: [
          {
            id: 'Q2hhbXAtNg==',
            type: 'text',
            label: "Saisir le n°RNA de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtNw==',
            type: 'yes_no',
            label: "L'association ou la congrégation ne dispose pas de n° RNA",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOA==',
            type: 'departements',
            label: 'Département de rattachement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtOQ==',
            type: 'text',
            label: "Titre de l'association",
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTA=',
            type: 'text',
            label: 'Adresse du siège social',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTI=',
            type: 'text',
            label: 'Numéro de téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTE=',
            type: 'email',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTQ=',
            type: 'text',
            label: 'Site internet',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTU=',
            type: 'text',
            label: 'Civilité',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTY=',
            type: 'text',
            label: 'NOM',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTc=',
            type: 'text',
            label: 'Prénom',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTg=',
            type: 'address',
            label: 'Adresse',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMTk=',
            type: 'text',
            label: 'N° appartement, boîte aux lettres, étage, couloir',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjA=',
            type: 'text',
            label: 'Immeuble - Bâtiment - Résidence',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjE=',
            type: 'text',
            label: 'Lieu dit, Boîte postale',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjI=',
            type: 'phone',
            label: 'Téléphone',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjM=',
            type: 'text',
            label: 'Courriel de contact',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjQ=',
            type: 'textarea',
            label: 'Type de financement',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjU=',
            type: 'text',
            label: 'Chargement de la matrice complétée de la déclaration',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
          {
            id: 'Q2hhbXAtMjY=',
            type: 'yes_no',
            label: 'Dossier sensible ?',
            description: '',
            required: false,
            options: null,
            champDescriptors: null,
          },
        ],
        annotationDescriptors: [],
      },
    ],
    groupeInstructeurs: [
      {
        id: 'R3JvdXBlSW5zdHJ1Y3RldXItMg==',
        number: 2,
        label: 'défaut',
        instructeurs: [
          {
            id: 'SW5zdHJ1Y3RldXItMg==',
            email: 'mail@peng-fei.name',
          },
          {
            id: 'SW5zdHJ1Y3RldXItMw==',
            email: 'me@bastienchevallier.com',
          },
        ],
      },
    ],
    service: {
      id: 'U2VydmljZS0y',
      nom: 'DLPAJ',
      organisme: 'Direction des libertés publiques et des affaires juridiques',
      siret: '38103128500491',
      typeOrganisme: 'administration_centrale',
    },
  },
}
