export const routeNames = {
  HOME: 'Home',
  ABOUT: 'About',
  DOSSIERS: 'Dossiers',
  DEMARCHES: 'Demarches',
  DEMARCHEDOSSIERS: 'DemarcheDossiers',
  SIGNIN: 'SignIn',
  SIGNUP: 'SignUp',
  PROFILE: 'Profile',
  STATISTIQUES: 'Statistiques',
  LOGOUT: 'LogOut',
  USER: 'User',
  ADMIN: 'Admin',
  ROLE: 'Role',
  ORGANISMES: 'Organismes',
  LISTEORGANISMES: 'ListeOrganismes',
  FICHEORGANISME: 'FicheOrganisme',
  UPDATEPASSWORD: 'UpdatePassword',
  RESETPASSWORD: 'ResetPassword',
  Page404: '404',
  VALIDEMAIL: 'ValidEmail',
}
