export const routeNames = {
  ABOUT: 'About',
  ADMIN: 'Admin',
  CONFIGURATION_DEMARCHES: 'Configuration',
  DEMARCHES: 'Démarches',
  DEMARCHE_DOSSIERS: 'DemarcheDossiers',
  DOSSIERS: 'Dossiers',
  FICHE_ORGANISME: 'FicheOrganisme',
  LISTE_ORGANISMES: 'ListeOrganismes',
  LIST_USERS: 'ListUsers',
  LOGOUT: 'LogOut',
  ORGANISMES: 'Organismes',
  PROFILE: 'Profile',
  Page_404: '404',
  RESET_PASSWORD: 'ResetPassword',
  ROLE: 'Role',
  SIGNIN: 'SignIn',
  SIGNUP: 'SignUp',
  STATISTIQUES: 'Statistiques',
  UPDATE_PASSWORD: 'UpdatePassword',
  USER: 'User',
  VALIDE_MAIL: 'ValidEmail',
  ACCESSIBILITY: 'Accessibility',
} as const
