export const routeNames = {
  HOME: 'Home',
  ABOUT: 'About',
  DOSSIERS: 'Dossiers',
  DEMARCHES: 'Demarches',
  DEMARCHE_DOSSIERS: 'DemarcheDossiers',
  SIGNIN: 'SignIn',
  SIGNUP: 'SignUp',
  PROFILE: 'Profile',
  STATISTIQUES: 'Statistiques',
  LOGOUT: 'LogOut',
  USER: 'User',
  ADMIN: 'Admin',
  ROLE: 'Role',
  ORGANISMES: 'Organismes',
  LISTE_ORGANISMES: 'ListeOrganismes',
  FICHE_ORGANISME: 'FicheOrganisme',
  UPDATE_PASSWORD: 'UpdatePassword',
  RESET_PASSWORD: 'ResetPassword',
  Page_404: '404',
  VALIDE_MAIL: 'ValidEmail',
} as const
