#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm lint

echo "============================================"
echo "==                                        =="
echo "==   Remember to run tests before push!  =="
echo "==                                        =="
echo "============================================"
sleep 1
