import { eJobPosition, eQualityInOrganisme } from '@biblio-num/shared'
import type { IFoundationOutput } from '@biblio-num/shared'

export const mockFoundationPayload: IFoundationOutput = {
  id: 'OO1-FRUP-000123-01',
  createdAt: new Date('2018-06-01T12:00:00Z'),
  updatedAt: new Date('2024-04-10T09:15:00Z'),
  state: 'Active',
  stateEffectiveAt: new Date('2024-04-10T09:15:00Z'),
  siret: '98765432100012',
  creationAt: new Date('2018-05-20T00:00:00Z'),
  title: 'Fondation pour l\'Enfance',
  address: {
    oneLine: '33 Avenue des Frères Lumière 69008 Lyon',
    coordinates: [6.154443, 47.618889],
    rnaAddress: null,
    dsAddress: {
      cityName: 'Lyon',
      cityCode: '69128',
      label: '33 Avenue des Frères Lumière 69008 Lyon',
      postalCode: '69008',
      type: 'housenumber',
      countryCode: 'FR',
      countryName: 'France',
      departmentName: 'Rhône',
      departmentCode: 'D69',
      regionName: 'Auvergne-Rhône-Alpes',
      regionCode: '84',
      streetAddress: 'Avenue des Frères Lumière',
      streetNumber: '33',
      streetName: 'Avenue des Frères Lumière',
    },
  },
  email: 'direction@fondation-enfance.org',
  phone: '01 88 00 11 22',
  department: 'D69',
  socialObject: 'Soutenir les projets innovants en faveur de l\'éducation et de la protection de l\'enfance.',
  website: 'https://www.fondation-enfance.org',
  files: [
    {
      id: 'f3-uuid-comptes-fondation',
      createdAt: new Date('2024-04-10T09:15:00Z'),
      updatedAt: new Date('2024-04-10T09:15:00Z'),
      originalName: 'comptes_annuels_2023.zip',
      checksum: 'xyz987uvw654',
      byteSize: 2500800,
      mimeType: 'application/zip',
      name: 'Comptes 2023',
      uploadedAt: new Date('2024-04-10T09:15:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Comptes',
      effectiveAt: new Date('2023-12-31T00:00:00Z'),
      rnaFile: null,
    },
  ],
  publicGenerosityYears: [2022, 2023],
  publicSubsidyYears: [],
  foreignFinancingYears: [2023],
  dueDate: new Date('2024-04-10T09:15:00Z'),
  hasInternationalActivity: true,
  fiscalEndAt: new Date('2024-12-31T23:59:59Z'),
  accountDepositYears: [2022, 2023],
  persons: [
    {
      id: 'p2-uuid-martin',
      lastName: 'Martin',
      firstName: 'Pierre',
      bornAt: new Date('1975-11-02T00:00:00Z'),
      address: {
        oneLine: '15 Boulevard des Belges 69006 Lyon',
        coordinates: [45.772, 4.853],
        rnaAddress: null,
        dsAddress: {
          cityName: 'Lyon',
          cityCode: '69126',
          label: '15 Boulevard des Belges 69006 Lyon',
          postalCode: '69006',
          type: 'housenumber',
          countryCode: 'FR',
          countryName: 'France',
          departmentName: 'Rhône',
          departmentCode: 'D69',
          regionName: 'Auvergne-Rhône-Alpes',
          regionCode: '84',
          streetAddress: 'Boulevard des Belges',
          streetNumber: '15',
          streetName: 'Boulevard des Belges',
        },
      },
      civility: 'M.',
      email: 'p.martin@perso.fr',
      phone: '06 99 88 77 66',
      profession: 'Avocat',
      nationality: 'Française',
      bornPlace: 'Marseille',
      isFounder: false,
      residenceCountry: 'France',
      entryAt: new Date('2019-01-15T00:00:00Z'),
      exitAt: null,
      jobPosition: eJobPosition.Président,
      quality: eQualityInOrganisme['Membre du conseil d\'administration'],
    },
    {
      id: 'p3-uuid-bernard',
      lastName: 'Bernard',
      firstName: 'Sophie',
      bornAt: new Date('1982-03-20T00:00:00Z'),
      address: null,
      civility: 'Mme',
      email: 's.bernard@fondation-enfance.org',
      phone: '07 72 00 11 23',
      profession: 'Directrice',
      nationality: 'Suisse',
      bornPlace: 'Genève',
      isFounder: true,
      residenceCountry: 'France',
      entryAt: new Date('2018-06-01T00:00:00Z'),
      exitAt: null,
      jobPosition: eJobPosition.Secrétaire,
      quality: eQualityInOrganisme['Membre du conseil d\'administration'],

    },
  ],
  founderLegalEntities: [
    {
      type: 'FRUP',
      publicId: 'Fondation handisport judo 2',
    },
  ],
  foundedLegalEntities: [
    {
      type: 'FRUP',
      publicId: 'Fondation Ecole du sud',
    },
    {
      type: 'FRUP',
      publicId: 'Fondation Nicolas Hulot pour la Nature et l\'Homme',
    },
  ],
  governanceLegalEntities: [
    {
      type: 'Fondation',
      publicId: 'F-000001-01',
    },
  ],
  fromLineage: null,
  toLineage: null,
  foundationType: 'FRUP',
  generalInterestDomain: 'Éducation et enfance',
  events: [
    {
      publishedJoafAt: new Date('2018-06-05T00:00:00Z'),
      demarcheName: 'Reconnaissance d\'utilité publique',
      demarcheNumber: 500,
      dossierNumber: 12345,
      acceptedAt: new Date('2018-05-20T00:00:00Z'),
      organismeBefore: null,
    },
  ],
}
