import type { siafV2 } from '@biblio-num/shared'

export const mockAssociationPayload: siafV2.IAssociationOutput = {
  _id: '6724abf1-f091-4e76-8f55-011c7b8e1a7b',
  _createdAt: new Date('2020-01-15T10:00:00Z'),
  _updatedAt: new Date('2024-05-20T15:30:00Z'),
  publicId: 'W751001234',
  status: 'Active',
  statusEffectiveAt: null,
  siret: '44 261 581 100 019',
  creationAt: new Date('2020-01-10T00:00:00Z'),
  title: 'Association Les Amis de la Nature',
  address: {
    oneLine: '10 Rue des Peupliers 75013 Paris',
    coordinates: [2.326, 48.833],
    rnaAddress: {
      address: {
        complement: 'Bâtiment A',
        numvoie: '10',
        repetition: null,
        typevoie: 'RUE',
        libvoie: 'DES PEUPLIERS',
        distrib: '75013 PARIS 13',
        codeinsee: '75113',
        codepostal: '75013',
        libcommune: 'PARIS 13',
      },
      gouvAddress: {
        label: '10 Rue des Peupliers 75013 Paris',
        housenumber: '10',
        id: '75113_7162_00010',
        name: '10 Rue des Peupliers',
        postcode: '75013',
        citycode: '75113',
        city: 'Paris',
        district: 'Paris 13e Arrondissement',
        context: '75, Paris, Île-de-France',
        type: 'housenumber',
        street: 'Rue des Peupliers',
      },
    },
    dsAddress: null,
  },
  email: 'contact@amis-nature.fr',
  phone: '01 88 45 67 89',
  department: '75',
  socialObject: 'Protéger l\'environnement local et sensibiliser le public à la biodiversité.',
  website: 'https://www.amis-nature.fr',
  files: [
    {
      _id: 'f1-uuid-statuts-2018',
      _createdAt: new Date('2018-05-20T10:00:00Z'),
      _updatedAt: new Date('2018-05-20T10:00:00Z'),
      originalName: 'statuts_initiaux.pdf',
      checksum: 'abc123def456',
      byteSize: 150240,
      mimeType: 'application/pdf',
      name: 'Statuts initiaux 2018',
      uploadedAt: new Date('2018-05-20T10:00:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Statuts',
      effectiveAt: new Date('2018-05-20T00:00:00Z'),
      rnaFile: null,
    },
    {
      _id: 'f2-uuid-statuts-2023',
      _createdAt: new Date('2023-03-10T11:00:00Z'),
      _updatedAt: new Date('2023-03-10T11:00:00Z'),
      originalName: 'statuts_signes_2023.pdf',
      checksum: 'def456ghi789',
      byteSize: 210500,
      mimeType: 'application/pdf',
      name: 'Statuts mis à jour 2023',
      uploadedAt: new Date('2023-03-10T11:00:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Statuts',
      effectiveAt: new Date('2023-03-01T00:00:00Z'),
      rnaFile: null,
    },
    {
      _id: 'f3-uuid-comptes-2022',
      _createdAt: new Date('2023-06-15T09:00:00Z'),
      _updatedAt: new Date('2023-06-15T09:00:00Z'),
      originalName: 'comptes_annuels_2022.zip',
      checksum: 'ghi789jkl012',
      byteSize: 1250800,
      mimeType: 'application/zip',
      name: 'Comptes annuels 2022',
      uploadedAt: new Date('2023-06-15T09:00:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Comptes',
      effectiveAt: new Date('2022-12-31T00:00:00Z'),
      rnaFile: null,
    },
    {
      _id: 'f4-uuid-comptes-2023',
      _createdAt: new Date('2024-06-10T09:15:00Z'),
      _updatedAt: new Date('2024-06-10T09:15:00Z'),
      originalName: 'rapport_financier_2023.pdf',
      checksum: 'jkl012mno345',
      byteSize: 850400,
      mimeType: 'application/pdf',
      name: 'Rapport financier 2023',
      uploadedAt: new Date('2024-06-10T09:15:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Comptes',
      effectiveAt: new Date('2023-12-31T00:00:00Z'),
      rnaFile: null,
    },
    {
      _id: 'f5-uuid-rapport-activite',
      _createdAt: new Date('2024-06-10T09:16:00Z'),
      _updatedAt: new Date('2024-06-10T09:16:00Z'),
      originalName: 'RA_2023_complet.pdf',
      checksum: 'mno345pqr678',
      byteSize: 3500200,
      mimeType: 'application/pdf',
      name: 'Rapport d\'activité 2023',
      uploadedAt: new Date('2024-06-10T09:16:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Rapport d\'activité',
      effectiveAt: new Date('2023-12-31T00:00:00Z'),
      rnaFile: null,
    },
    {
      _id: 'f6-uuid-jugement',
      _createdAt: new Date('2021-06-10T14:00:00Z'),
      _updatedAt: new Date('2021-06-10T14:00:00Z'),
      originalName: 'jugement_tgi_2021.pdf',
      checksum: 'pqr678stu901',
      byteSize: 400100,
      mimeType: 'application/pdf',
      name: 'Jugement TGI 2021',
      uploadedAt: new Date('2021-06-10T14:00:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Jugement',
      effectiveAt: new Date('2021-06-10T00:00:00Z'),
      rnaFile: null,
    },
    {
      _id: 'f7-uuid-recepisse-rna',
      _createdAt: new Date('2018-05-25T14:00:00Z'),
      _updatedAt: new Date('2018-05-25T14:00:00Z'),
      originalName: 'recepisse_creation.pdf',
      checksum: 'stu901vwx234',
      byteSize: 50120,
      mimeType: 'application/pdf',
      name: 'Récépissé de création',
      uploadedAt: new Date('2018-05-25T14:00:00Z'),
      prefixS3: 'rna',
      typeFile: null,
      effectiveAt: new Date('2018-05-25T00:00:00Z'),
      rnaFile: {
        typePiece: 'Récépissé délivré',
        typeRecepisse: 'Création',
        eventId: 'rna-event-1',
        uploadedAt: new Date('2018-05-25T14:00:00Z'),
      },
    },
    {
      _id: 'f8-uuid-acte-notarie',
      _createdAt: new Date('2022-11-05T16:00:00Z'),
      _updatedAt: new Date('2022-11-05T16:00:00Z'),
      originalName: 'acte_donation_martin.pdf',
      checksum: 'vwx234yza567',
      byteSize: 720300,
      mimeType: 'application/pdf',
      name: 'Acte de donation 2022',
      uploadedAt: new Date('2022-11-05T16:00:00Z'),
      prefixS3: 'fondation',
      typeFile: 'Acte notarié',
      effectiveAt: new Date('2022-11-05T00:00:00Z'),
      rnaFile: null,
    },
  ],
  publicGenerosityYears: [2022, 2023],
  publicSubsidyYears: [2023],
  foreignFinancingYears: [],
  dueDate: new Date('2025-06-30T23:59:59Z'),
  hasInternationalActivity: false,
  fiscalEndAt: new Date('2024-12-31T23:59:59Z'),
  accountDepositYears: [2022, 2023],
  persons: [
    {
      _id: 'p1-uuid-dupont',
      lastName: 'Dupont',
      firstName: 'Marie',
      bornAt: new Date('1980-05-15T00:00:00Z'),
      address: {
        oneLine: '10 Rue des Peupliers 75013 Paris',
        coordinates: [48.8315, 2.3569],
        rnaAddress: {
          address: {
            complement: 'Bâtiment A',
            numvoie: '10',
            repetition: null,
            typevoie: 'RUE',
            libvoie: 'DES PEUPLIERS',
            distrib: '75013 PARIS 13',
            codeinsee: '75113',
            codepostal: '75013',
            libcommune: 'PARIS 13',
          },
          gouvAddress: {
            label: '10 Rue des Peupliers 75013 Paris',
            housenumber: '10',
            id: '75113_7162_00010',
            name: '10 Rue des Peupliers',
            postcode: '75013',
            citycode: '75113',
            city: 'Paris',
            district: 'Paris 13e Arrondissement',
            context: '75, Paris, Île-de-France',
            type: 'housenumber',
            street: 'Rue des Peupliers',
          },
        },
        dsAddress: null,
      },
      civility: 'Mme',
      email: 'm.dupont@mail.com',
      phone: '0611223344',
      profession: 'Enseignante',
      nationality: 'Française',
      bornPlace: 'Lyon',
      isFounder: true,
      residenceCountry: 'France',
      entryAt: new Date('2020-01-10T00:00:00Z'),
      exitAt: null,
      jobPosition: 'Président',
      role: null,
    },
    {
      _id: 'p2-uuid-martin',
      lastName: 'Martin',
      firstName: 'Pierre',
      bornAt: new Date('1975-11-02T00:00:00Z'),
      address: {
        oneLine: '15 Boulevard des Belges 69006 Lyon',
        coordinates: [45.772, 4.853],
        rnaAddress: null,
        dsAddress: {
          cityName: 'Lyon',
          cityCode: '69126',
          label: '15 Boulevard des Belges 69006 Lyon',
          postalCode: '69006',
          type: 'housenumber',
          countryCode: 'FR',
          countryName: 'France',
          departmentName: 'Rhône',
          departmentCode: '69',
          regionName: 'Auvergne-Rhône-Alpes',
          regionCode: '84',
          streetAddress: 'Boulevard des Belges',
          streetNumber: '15',
          streetName: 'Boulevard des Belges',
        },
      },
      civility: 'M.',
      email: 'p.martin@perso.fr',
      phone: '0699887766',
      profession: 'Avocat',
      nationality: 'Française',
      bornPlace: 'Marseille',
      isFounder: false,
      residenceCountry: 'France',
      entryAt: new Date('2019-01-15T00:00:00Z'),
      exitAt: null,
      jobPosition: null,
      role: 'Membre du conseil d\'administration',
    },
    {
      _id: 'p3-uuid-bernard',
      lastName: 'Bernard',
      firstName: 'Sophie',
      bornAt: new Date('1982-03-20T00:00:00Z'),
      address: null,
      civility: 'Mme',
      email: 's.bernard@fondation-enfance.org',
      phone: '0472001123',
      profession: 'Directrice',
      nationality: 'Suisse',
      bornPlace: 'Genève',
      isFounder: true,
      residenceCountry: 'France',
      entryAt: new Date('2018-06-01T00:00:00Z'),
      exitAt: null,
      jobPosition: null,
      role: 'Personne exerçant des fonctions de direction',
    },
    {
      _id: 'p4-uuid-petit',
      lastName: 'Petit',
      firstName: 'Thomas',
      bornAt: new Date('1990-09-10T00:00:00Z'),
      address: {
        oneLine: '42 Rue Nationale 59800 Lille',
        coordinates: [50.636, 3.057],
        rnaAddress: null,
        dsAddress: {
          cityName: 'Lille',
          cityCode: '59350',
          label: '42 Rue Nationale 59800 Lille',
          postalCode: '59800',
          type: 'housenumber',
          countryCode: 'FR',
          countryName: 'France',
          departmentName: 'Nord',
          departmentCode: '59',
          regionName: 'Hauts-de-France',
          regionCode: '32',
          streetAddress: 'Rue Nationale',
          streetNumber: '42',
          streetName: 'Rue Nationale',
        },
      },
      civility: 'M.',
      email: 'thomas.petit@mail.pro',
      phone: '0700112233',
      profession: 'Comptable',
      nationality: 'Française',
      bornPlace: 'Lille',
      isFounder: false,
      residenceCountry: 'France',
      entryAt: new Date('2021-03-01T00:00:00Z'),
      exitAt: null,
      jobPosition: 'Trésorier',
      role: null,
    },
    {
      _id: 'p5-uuid-robert',
      lastName: 'Robert',
      firstName: 'Camille',
      bornAt: new Date('1985-12-05T00:00:00Z'),
      address: {
        oneLine: '1 Avenue de la République 75011 Paris',
        coordinates: [48.867, 2.368],
        rnaAddress: {
          address: {
            complement: null,
            numvoie: '1',
            repetition: null,
            typevoie: 'AVENUE',
            libvoie: 'DE LA REPUBLIQUE',
            distrib: '75011 PARIS 11',
            codeinsee: '75111',
            codepostal: '75011',
            libcommune: 'PARIS 11',
          },
          gouvAddress: {
            label: '1 Avenue de la République 75011 Paris',
            housenumber: '1',
            id: '75111_7942_00001',
            name: '1 Avenue de la République',
            postcode: '75011',
            citycode: '75111',
            city: 'Paris',
            district: 'Paris 11e Arrondissement',
            context: '75, Paris, Île-de-France',
            type: 'housenumber',
            street: 'Avenue de la République',
          },
        },
        dsAddress: null,
      },
      civility: 'Mme',
      email: 'camille.robert@gmail.com',
      phone: '0612345678',
      profession: 'Journaliste',
      nationality: 'Française',
      bornPlace: 'Bordeaux',
      isFounder: false,
      residenceCountry: 'France',
      entryAt: new Date('2022-06-15T00:00:00Z'),
      exitAt: null,
      jobPosition: 'Secrétaire',
      role: null,
    },
    {
      _id: 'p6-uuid-garcia',
      lastName: 'Garcia',
      firstName: 'Lucas',
      bornAt: new Date('1978-07-22T00:00:00Z'),
      address: null,
      civility: 'M.',
      email: 'lucas.garcia@etranger.es',
      phone: '+34910123456',
      profession: 'Ingénieur',
      nationality: 'Espagnole',
      bornPlace: 'Madrid',
      isFounder: false,
      residenceCountry: 'Espagne',
      entryAt: new Date('2020-01-10T00:00:00Z'),
      exitAt: null,
      jobPosition: 'Vice président',
      role: 'Membre du conseil de surveillance',
    },
    {
      _id: 'p7-uuid-leroy',
      lastName: 'Leroy',
      firstName: 'Manon',
      bornAt: new Date('1995-02-18T00:00:00Z'),
      address: {
        oneLine: '7 Rue de la Paix 44000 Nantes',
        coordinates: [47.214, -1.554],
        rnaAddress: null,
        dsAddress: {
          cityName: 'Nantes',
          cityCode: '44109',
          label: '7 Rue de la Paix 44000 Nantes',
          postalCode: '44000',
          type: 'housenumber',
          countryCode: 'FR',
          countryName: 'France',
          departmentName: 'Loire-Atlantique',
          departmentCode: '44',
          regionName: 'Pays de la Loire',
          regionCode: '52',
          streetAddress: 'Rue de la Paix',
          streetNumber: '7',
          streetName: 'Rue de la Paix',
        },
      },
      civility: 'Mme',
      email: 'manon.leroy@asso.fr',
      phone: null,
      profession: 'Étudiante',
      nationality: 'Française',
      bornPlace: 'Rennes',
      isFounder: false,
      residenceCountry: 'France',
      entryAt: new Date('2023-01-20T00:00:00Z'),
      exitAt: null,
      jobPosition: null,
      role: 'Membre du directoire',
    },
    {
      _id: 'p8-uuid-moreau',
      lastName: 'Moreau',
      firstName: 'Julien',
      bornAt: new Date('1965-04-30T00:00:00Z'),
      address: null,
      civility: 'M.',
      email: null,
      phone: '0145454545',
      profession: 'Retraité',
      nationality: 'Française',
      bornPlace: 'Paris',
      isFounder: true,
      residenceCountry: 'France',
      entryAt: new Date('2018-06-01T00:00:00Z'),
      exitAt: new Date('2023-06-01T00:00:00Z'),
      jobPosition: null,
      role: 'Membre du conseil d\'administration',
    },
    {
      _id: 'p9-uuid-nguyen',
      lastName: 'Nguyen',
      firstName: 'Linh',
      bornAt: new Date('1988-10-01T00:00:00Z'),
      address: {
        oneLine: '55 Rue du Faubourg Saint-Honoré 75008 Paris',
        coordinates: [48.87, 2.316],
        rnaAddress: {
          address: {
            complement: 'APT 12',
            numvoie: '55',
            repetition: null,
            typevoie: 'RUE',
            libvoie: 'DU FAUBOURG SAINT HONORE',
            distrib: '75008 PARIS 08',
            codeinsee: '75108',
            codepostal: '75008',
            libcommune: 'PARIS 08',
          },
          gouvAddress: {
            label: '55 Rue du Faubourg Saint-Honoré 75008 Paris',
            housenumber: '55',
            id: '75108_3469_00055',
            name: '55 Rue du Faubourg Saint-Honoré',
            postcode: '75008',
            citycode: '75108',
            city: 'Paris',
            district: 'Paris 8e Arrondissement',
            context: '75, Paris, Île-de-France',
            type: 'housenumber',
            street: 'Rue du Faubourg Saint-Honoré',
          },
        },
        dsAddress: null,
      },
      civility: 'Mme',
      email: 'linh.nguyen@mail.com',
      phone: '0655443322',
      profession: 'Designer',
      nationality: 'Vietnamienne',
      bornPlace: 'Hanoï',
      isFounder: false,
      residenceCountry: 'France',
      entryAt: new Date('2022-09-01T00:00:00Z'),
      exitAt: null,
      jobPosition: 'Secrétaire',
      role: null,
    },
    {
      _id: 'p10-uuid-schmidt',
      lastName: 'Schmidt',
      firstName: 'Hans',
      bornAt: new Date('1972-06-12T00:00:00Z'),
      address: {
        oneLine: '12 Karl-Liebknecht-Straße 10178 Berlin',
        coordinates: [52.521, 13.411],
        rnaAddress: null,
        dsAddress: {
          cityName: 'Berlin',
          cityCode: '11000000',
          label: '12 Karl-Liebknecht-Straße 10178 Berlin',
          postalCode: '10178',
          type: 'housenumber',
          countryCode: 'DE',
          countryName: 'Allemagne',
          departmentName: null,
          departmentCode: null,
          regionName: 'Berlin',
          regionCode: 'BE',
          streetAddress: 'Karl-Liebknecht-Straße',
          streetNumber: '12',
          streetName: 'Karl-Liebknet-Straße',
        },
      },
      civility: 'M.',
      email: 'h.schmidt@mail.de',
      phone: '+49301234567',
      profession: 'Architecte',
      nationality: 'Allemande',
      bornPlace: 'Berlin',
      isFounder: false,
      residenceCountry: 'Allemagne',
      entryAt: new Date('2021-11-15T00:00:00Z'),
      exitAt: null,
      jobPosition: null,
      role: 'Membre du conseil de surveillance',
    },
  ],
  founderLegalEntities: [
    {
      type: 'Entreprise',
      publicId: '12345678900010',
    },
  ],
  foundedLegalEntities: [
    {
      type: 'Association',
      publicId: 'W751009876',
    },
  ],
  governanceLegalEntities: [
    {
      type: 'Fondation',
      publicId: 'F-000456-01',
    },
    {
      type: 'Entreprise',
      publicId: '98765432100020',
    },
  ],
  fromLineage: {
    organismes: [
      {
        kind: 'Association',
        publicId: 'W751001111',
      },
      {
        kind: 'Association',
        publicId: 'W751002222',
      },
    ],
    type: 'Fusion',
    at: new Date('2018-01-01T00:00:00Z'),
  },
  toLineage: null,
  activityDomainCode: '160000',
  activityDomainDescription: 'Environnement, cadre de vie',
  union: {
    associationPublicIds: ['W752004567'],
    unionKind: 'Union',
    since: new Date('2022-01-01T00:00:00Z'),
  },
  quality: {
    type: 'Reconnue d\'utilité publique',
    startedAt: new Date('2023-01-01T00:00:00Z'),
    endedAt: null,
  },
  secondaryEstablishments: [],
  acquiredEstablishments: [
    {
      name: 'Local rue du Parc',
      address: {
        oneLine: '5 Rue du Parc 75014 Paris',
        coordinates: [48.833, 2.326],
        rnaAddress: null,
        dsAddress: {
          cityName: 'Paris',
          cityCode: '75114',
          label: '5 Rue du Parc 75014 Paris',
          postalCode: '75014',
          type: 'housenumber',
          countryCode: 'FR',
          countryName: 'France',
          departmentName: 'Paris',
          departmentCode: '75',
          regionName: 'Île-de-France',
          regionCode: '11',
          streetAddress: 'Rue du Parc',
          streetNumber: '5',
          streetName: 'Rue du Parc',
        },
      },
      type: 'Immeuble de rapport',
      value: 150000,
      acquiredType: 'onéreux',
    },
  ],
  cededEstablishments: [],
  rnaEvents: [],
  events: [
    {
      publishedJoafAt: null,
      demarcheName: 'Dépôt des comptes',
      demarcheNumber: 1234,
      dossierNumber: 98765,
      acceptedAt: new Date('2024-05-15T10:00:00Z'),
      organismeBefore: null,
    },
  ],
}
