name: CI of biblio-num
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - 'main'

jobs:
  client:
    name: client - Run unit tests 
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: run test unit FRONT
        run: | 
            npm i -g pnpm
            pnpm i --frozen-lockfile
            pnpm run lint:client
            pnpm run test:client
      - name: run build
        run: |
            pnpm run build:client

  server: 
    name: server - Run unit tests 
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: run test unit BACK-END
        run: | 
            npm i -g pnpm
            pnpm i --frozen-lockfile
            pnpm run lint:server
            pnpm run docker:db:up
            pnpm run test:server
            pnpm run docker:db:down
      - name: run build
        run: |
            pnpm run build:server
