name: Release - Bibliothéque numérique
on: 
  workflow_dispatch:
    branches: 
      - main
  # TODO: Redéfinir process le workflow de la création de release
  # workflow_run:
  #   workflows: ["ci.yml"]
  #   types: [completed]
  #   branches: ["main"]

jobs:
  tests:
    name: Run unit tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'
      - name: create release
        uses:  google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
